version: "3"
services:
  api:
    build:
      context: .
      dockerfile: broker-routes/Dockerfile
    ports:
      - "3000:3000" # Porta em que a sua API Node.js está rodando

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
