version: "3"
services:
  api:
    build:
      context: .
      dockerfile: broker-in/Dockerfile
    ports:
      - "3000:3000" # Porta em que a sua API Node.js está rodando

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "my-rabbitmq"
    ports:
      - "5672:5672" # Porta para conexões AMQP
      - "15672:15672" # Porta para o painel de controle da RabbitMQ UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
    driver: local
